# Common configuration shared between all applications
configserver:
    name: Docker JBooter Registry
    status: Connected to the JBooter Registry running in Docker

jbooter:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production

eureka:
    client:
        service-url:
            defaultZone: http://admin:${jbooter.registry.password}@localhost:8761/eureka/
